/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminalrecordsystem;

import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class CriminalLog extends javax.swing.JFrame {

    /**
     * Creates new form CriminalLog
     */
    public CriminalLog() {
        initComponents();
        scaleimage();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void scaleimage() {
//     ImageIcon icon6=new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\CriminalRecordSystem\\images\\police_badge_PNG72.png");
//        ImageIcon icon7=new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\CriminalRecordSystem\\images\\Karachi-Mazar-E-Quaid-1024x1024.png");
//        ImageIcon icon8=new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\CriminalRecordSystem\\images\\Lahore-Minar-E-Pakistan-1024x1024.png");
//        ImageIcon icon9=new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\CriminalRecordSystem\\images\\Balochistan.jpeg");
//        ImageIcon icon5=new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\CriminalRecordSystem\\images\\kpk.PNG");
//        ImageIcon icon100=new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\CriminalRecordSystem\\images\\back.png");
//      ImageIcon icon4=new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\CriminalRecordSystem\\images\\police_badge_PNG72.png");
//          
//    // police logo
//         Image img6=icon6.getImage();
//        Image imgscale6=img6.getScaledInstance(jLabel16.getWidth(), jLabel16.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledImage6 = new ImageIcon(imgscale6);
//        jLabel16.setIcon(scaledImage6);
//        //sindh
//        Image img7=icon7.getImage();
//        Image imgscale7=img7.getScaledInstance(jLabel15.getWidth(), jLabel15.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledImage7 = new ImageIcon(imgscale7);
//        jLabel15.setIcon(scaledImage7);
//        //punjab
//        Image img8=icon8.getImage();
//        Image imgscale8=img8.getScaledInstance(jLabel22.getWidth(), jLabel22.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledImage8 = new ImageIcon(imgscale8);
//        jLabel22.setIcon(scaledImage8);
//        //balochistan
//        Image img9=icon9.getImage();
//        Image imgscale9=img9.getScaledInstance(jLabel31.getWidth(), jLabel31.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledImage9 = new ImageIcon(imgscale9);
//        jLabel31.setIcon(scaledImage9);
//        //kpk
//        Image img5=icon5.getImage();
//        Image imgscale5=img5.getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledImage5 = new ImageIcon(imgscale5);
//        jLabel9.setIcon(scaledImage5);
//        //back
//        Image img100=icon100.getImage();
//        Image imgscale100 =img100.getScaledInstance(back.getWidth(), back.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledImage100 = new ImageIcon(imgscale100);
//        back.setIcon(scaledImage100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        punjab = new javax.swing.JButton();
        sindh1 = new javax.swing.JButton();
        balochistan = new javax.swing.JButton();
        kpk = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setOpaque(true);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        punjab.setBorderPainted(false);
        punjab.setContentAreaFilled(false);
        punjab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punjabActionPerformed(evt);
            }
        });
        jPanel1.add(punjab, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 240, 250));

        sindh1.setBorderPainted(false);
        sindh1.setContentAreaFilled(false);
        sindh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sindh1ActionPerformed(evt);
            }
        });
        jPanel1.add(sindh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 240, 240));

        balochistan.setBorderPainted(false);
        balochistan.setContentAreaFilled(false);
        balochistan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balochistanActionPerformed(evt);
            }
        });
        jPanel1.add(balochistan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 240, 250));

        kpk.setBorderPainted(false);
        kpk.setContentAreaFilled(false);
        kpk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpkActionPerformed(evt);
            }
        });
        jPanel1.add(kpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, 250, 250));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criminalrecordsystem/Criminallog.PNG"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 1190, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        HomePage e = new HomePage();
        e.setLocationRelativeTo(null);
        e.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void punjabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punjabActionPerformed
        try {
            // TODO add your handling code here:
            dispose();
            PunjabCriminals s = new PunjabCriminals();
            s.setLocationRelativeTo(null);
            s.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(CriminalLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_punjabActionPerformed

    private void sindh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sindh1ActionPerformed
        try {
            // TODO add your handling code here:
            dispose();
            SindhCriminals s = new SindhCriminals();
            s.setLocationRelativeTo(null);
            s.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(CriminalLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sindh1ActionPerformed

    private void balochistanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balochistanActionPerformed
        try {
            // TODO add your handling code here:
            dispose();
            BalochistanCriminals s = new BalochistanCriminals();
            s.setLocationRelativeTo(null);
            s.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(CriminalLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_balochistanActionPerformed

    private void kpkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpkActionPerformed
        try {
            // TODO add your handling code here:
            dispose();
            KPKCriminals s = new KPKCriminals();
            s.setLocationRelativeTo(null);
            s.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(CriminalLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kpkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriminalLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriminalLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriminalLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriminalLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriminalLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton balochistan;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kpk;
    private javax.swing.JButton punjab;
    private javax.swing.JButton sindh1;
    // End of variables declaration//GEN-END:variables
}
